version: "3.0"

services:
  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    ports:
      - "1080:80"
    volumes:
      - ./:/var/www/laravelStart
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=dev.laravel_nginx,localhost
    links:
      - "php:php"
    networks:
      - laravel_network

  php:
    container_name: laravel_php
    build: ./docker/php
    volumes:
      - ./:/var/www/laravelStart
    links:
      - "postgres:postgres"
    networks:
      - laravel_network

  postgres:
    image: postgres:11
    container_name: laravel_postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=postgres
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
